version: '2'

services:
  skinny:
    ports:
      - "1916:1916"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - FOLLOWS_SERVICE_HOST=follows_service
      - ARTICLE_SERVICE_HOST=article_service
      - FEED_SERVICE_HOST=feed_service
      - CREATE_SERVICE_HOST=create_service
  feed_service:
    build:
      context: ./services/feed
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - LOGGER_SERVICE_HOST=logger_service
  follows_service:
    build:
      context: ./services/follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
  logger_service:
    build:
      context: ./services/logger
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  article_service:
    build:
      context: ./services/article
      dockerfile: Dockerfile
    depends_on:
      - "database_service"
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - CREATE_SERVICE_HOST=create_service
  create_service:
    build:
      context: ./services/activities/create
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
  markdown_service:
    build:
      context: ./services/mdc
      dockerfile: Dockerfile
    volumes:
      - .:/repo
