version: '2'

networks:
  testnetwork:
    driver: bridge

services:
  skinny:
    ports:
      - "${SKINNY_SERVER_PORT}:${SKINNY_SERVER_PORT}"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - testnetwork
      - default
    environment:
      - SKINNY_SERVER_PORT=${SKINNY_SERVER_PORT}
      - USERS_SERVICE_HOST=users_service
      - DB_SERVICE_HOST=database_service
      - FOLLOWS_SERVICE_HOST=follows_service
      - ARTICLE_SERVICE_HOST=article_service
      - FEED_SERVICE_HOST=feed_service
      - CREATE_SERVICE_HOST=create_service
  feed_service:
    build:
      context: ./services/feed
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
  users_service:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "logger_service"
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
      args:
        - DBPATH=/repo/rabble.db
    volumes:
      - .:/repo
    depends_on:
      - "logger_service"
    environment:
      - LOGGER_SERVICE_HOST=logger_service
  follows_service:
    build:
      context: ./services/follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
  logger_service:
    build:
      context: ./services/logger
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  article_service:
    build:
      context: ./services/article
      dockerfile: Dockerfile
    depends_on:
      - "database_service"
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - CREATE_SERVICE_HOST=create_service
      - MDC_SERVICE_HOST=markdown_service
  create_service:
    build:
      context: ./services/activities/create
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    networks:
      - testnetwork
      - default
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - ARTICLE_SERVICE_HOST=article_service
      - HOST_NAME=skinny:${SKINNY_SERVER_PORT}
  follow_activity_service:
    build:
      context: ./services/activities/follow
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - testnetwork
      - default
    environment:
      - LOGGER_SERVICE_HOST=logger_service
  markdown_service:
    build:
      context: ./services/mdc
      dockerfile: Dockerfile
    volumes:
      - .:/repo
