version: '2'

services:
  skinny:
    ports:
      - "1916:1916"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - FOLLOWS_SERVICE_HOST=follows_service
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  follows_service:
    build:
      context: ./services/follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
