version: '2'

services:
  skinny:
    ports:
      - "1916:1916"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_microservice:
    build:
      context: ./services/example_microservice
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_go_microservice:
    build:
      context: ./services/example_go_python_microservice/go
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_python_microservice:
    build:
      context: ./services/example_go_python_microservice/python
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    volumes:
      - .:/repo

