version: '2'

services:
  skinny:
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_microservice:
    build:
      context: ./services/example_microservice
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_go_microservice:
    build:
      context: ./services/example_go_python_microservice/go_docker
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_python_microservice:
    build:
      context: ./services/example_go_python_microservice/python_docker
      dockerfile: Dockerfile
    volumes:
      - .:/repo
