version: '2'

services:
  skinny:
    ports:
      - "1916:1916"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - GO_SERVER_HOST=example_go_microservice
      - DB_SERVICE_HOST=database_service
  example_go_microservice:
    build:
      context: ./services/example_go_python_microservice/go
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  example_python_microservice:
    build:
      context: ./services/example_go_python_microservice/python
      dockerfile: Dockerfile
    depends_on:
      - "example_go_microservice"
    volumes:
      - .:/repo
    environment:
      - GO_SERVER_HOST=example_go_microservice
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  follows_service:
    build:
      context: ./services/follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service

