version: '2'

networks:
  rabble_testnetwork:
    external: true

services:
  skinny2:
    ports:
      - "${SKINNY_SERVER_PORT}:${SKINNY_SERVER_PORT}"
    build:
      context: ./skinny
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - rabble_testnetwork
      - default
    environment:
      - SKINNY_SERVER_PORT=${SKINNY_SERVER_PORT}
      - DB_SERVICE_HOST=database_service
      - USERS_SERVICE_HOST=users_service
      - FOLLOWS_SERVICE_HOST=follows_service2
      - ARTICLE_SERVICE_HOST=article_service
      - FEED_SERVICE_HOST=feed_service
      - CREATE_SERVICE_HOST=create_service2
      - LDNORM_SERVICE_HOST=ldnorm_service
      - RSS_SERVICE_HOST=rss_service
      - FOLLOW_ACTIVITY_SERVICE_HOST=follow_activity_service2
      - LIKE_SERVICE_HOST=like_service2
      - APPROVER_SERVICE_HOST=approver_service2
      - FOLLOW_RECOMMENDATIONS_HOST=recommend_follows_service
  feed_service:
    build:
      context: ./services/feed
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
  users_service:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "logger_service"
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
  like_service2:
    build:
      context: ./services/activities/like
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - rabble_testnetwork
      - default
    depends_on:
      - "logger_service"
    environment:
      - LOGGER_SERVICE_HOST=logger_service
      - DB_SERVICE_HOST=database_service
      - HOST_NAME=${SKINNY_SERVER_HOST}:${SKINNY_SERVER_PORT}
  ldnorm_service:
    build:
      context: ./services/ldnormaliser
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "logger_service"
    environment:
      - LOGGER_SERVICE_HOST=logger_service
  database_service:
    build:
      context: ./services/database
      dockerfile: Dockerfile
      args:
        - DBPATH=/repo/rabble2.db
    volumes:
      - .:/repo
    depends_on:
      - "logger_service"
    environment:
      - LOGGER_SERVICE_HOST=logger_service
  follows_service2:
    build:
      context: ./services/follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - rabble_testnetwork
      - default
    depends_on:
      - "database_service"
      - "approver_service2"
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - RSS_SERVICE_HOST=rss_service
      - FOLLOW_ACTIVITY_SERVICE_HOST=follow_activity_service2
      - APPROVER_SERVICE_HOST=approver_service2
      - HOST_NAME=${SKINNY_SERVER_HOST}:${SKINNY_SERVER_PORT}
  logger_service:
    build:
      context: ./services/logger
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  article_service:
    build:
      context: ./services/article
      dockerfile: Dockerfile
    depends_on:
      - "database_service"
    volumes:
      - .:/repo
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - CREATE_SERVICE_HOST=create_service2
      - MDC_SERVICE_HOST=markdown_service
  create_service2:
    build:
      context: ./services/activities/create
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    networks:
      - rabble_testnetwork
      - default
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - ARTICLE_SERVICE_HOST=article_service
      - HOST_NAME=${SKINNY_SERVER_HOST}:${SKINNY_SERVER_PORT}
  approver_service2:
    build:
      context: ./services/activities/approver
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    networks:
      - rabble_testnetwork
      - default
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
      - HOST_NAME=${SKINNY_SERVER_HOST}:${SKINNY_SERVER_PORT}
  follow_activity_service2:
    build:
      context: ./services/activities/follow
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    networks:
      - rabble_testnetwork
      - default
    environment:
      - LOGGER_SERVICE_HOST=logger_service
      - FOLLOWS_SERVICE_HOST=follows_service2
  markdown_service:
    build:
      context: ./services/mdc
      dockerfile: Dockerfile
    volumes:
      - .:/repo
  rss_service:
    build:
      context: ./services/rss
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    environment:
      - DB_SERVICE_HOST=database_service
      - ARTICLE_SERVICE_HOST=article_service
      - MDC_SERVICE_HOST=markdown_service
      - HOST_NAME=${SKINNY_SERVER_HOST}:${SKINNY_SERVER_PORT}
  recommend_follows_service:
    build:
      context: ./services/recommend_follows
      dockerfile: Dockerfile
    volumes:
      - .:/repo
    depends_on:
      - "database_service"
    environment:
      - DB_SERVICE_HOST=database_service
      - LOGGER_SERVICE_HOST=logger_service
